# Form implementation generated from reading ui file 'TicketPurchase.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_ticketWindow(object):
    def setupUi(self, ticketWindow):
        ticketWindow.setObjectName("ticketWindow")
        ticketWindow.resize(1106, 958)
        self.centralwidget = QtWidgets.QWidget(parent=ticketWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbTicketPurhcase = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbTicketPurhcase.setGeometry(QtCore.QRect(0, 0, 1101, 921))
        self.tbTicketPurhcase.setObjectName("tbTicketPurhcase")
        self.tabTicketPurchase = QtWidgets.QWidget()
        self.tabTicketPurchase.setObjectName("tabTicketPurchase")
        self.lblName = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblName.setGeometry(QtCore.QRect(180, 150, 121, 31))
        self.lblName.setObjectName("lblName")
        self.lblAge = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblAge.setGeometry(QtCore.QRect(180, 210, 121, 31))
        self.lblAge.setObjectName("lblAge")
        self.txtName = QtWidgets.QLineEdit(parent=self.tabTicketPurchase)
        self.txtName.setGeometry(QtCore.QRect(310, 150, 113, 31))
        self.txtName.setObjectName("txtName")
        self.txtAge = QtWidgets.QLineEdit(parent=self.tabTicketPurchase)
        self.txtAge.setGeometry(QtCore.QRect(310, 210, 113, 31))
        self.txtAge.setObjectName("txtAge")
        self.cmbSelection = QtWidgets.QComboBox(parent=self.tabTicketPurchase)
        self.cmbSelection.setGeometry(QtCore.QRect(310, 290, 111, 31))
        self.cmbSelection.setObjectName("cmbSelection")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.cmbSelection.addItem("")
        self.lblSelection = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblSelection.setGeometry(QtCore.QRect(180, 290, 121, 31))
        self.lblSelection.setObjectName("lblSelection")
        self.grpNumberOfTickets = QtWidgets.QGroupBox(parent=self.tabTicketPurchase)
        self.grpNumberOfTickets.setGeometry(QtCore.QRect(520, 170, 261, 131))
        self.grpNumberOfTickets.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grpNumberOfTickets.setFlat(False)
        self.grpNumberOfTickets.setCheckable(False)
        self.grpNumberOfTickets.setObjectName("grpNumberOfTickets")
        self.rb1 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rb1.setGeometry(QtCore.QRect(10, 30, 110, 24))
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rb2.setGeometry(QtCore.QRect(10, 60, 110, 24))
        self.rb2.setObjectName("rb2")
        self.rb3 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rb3.setGeometry(QtCore.QRect(10, 90, 110, 24))
        self.rb3.setObjectName("rb3")
        self.btnCost = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnCost.setGeometry(QtCore.QRect(180, 380, 101, 31))
        self.btnCost.setObjectName("btnCost")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(180, 440, 101, 31))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnClear = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnClear.setGeometry(QtCore.QRect(490, 550, 101, 31))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.tabTicketPurchase)
        self.btnExit.setGeometry(QtCore.QRect(690, 550, 101, 31))
        self.btnExit.setObjectName("btnExit")
        self.lblTotalCost = QtWidgets.QLabel(parent=self.tabTicketPurchase)
        self.lblTotalCost.setGeometry(QtCore.QRect(380, 380, 121, 31))
        self.lblTotalCost.setObjectName("lblTotalCost")
        self.txtAge_2 = QtWidgets.QLineEdit(parent=self.tabTicketPurchase)
        self.txtAge_2.setGeometry(QtCore.QRect(480, 380, 113, 31))
        self.txtAge_2.setObjectName("txtAge_2")
        self.tbTicketPurhcase.addTab(self.tabTicketPurchase, "")
        self.tabPurchasesMade = QtWidgets.QWidget()
        self.tabPurchasesMade.setObjectName("tabPurchasesMade")
        self.lstPurchasesMade = QtWidgets.QListWidget(parent=self.tabPurchasesMade)
        self.lstPurchasesMade.setGeometry(QtCore.QRect(30, 40, 1041, 341))
        self.lstPurchasesMade.setObjectName("lstPurchasesMade")
        self.tbTicketPurhcase.addTab(self.tabPurchasesMade, "")
        ticketWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ticketWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 26))
        self.menubar.setObjectName("menubar")
        ticketWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ticketWindow)
        self.statusbar.setObjectName("statusbar")
        ticketWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ticketWindow)
        self.tbTicketPurhcase.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ticketWindow)
        
        self.price_dictionary = self.load_data("price.txt")
        
        self.btnCost.clicked.connect(self.calculate_cost)
        self.btnPurchase.clicked.connect(self.purchase_made)
        self.btnClear.clicked.connect(self.clear)
        self.tbTicketPurhcase.currentChanged.connect(self.display_data)

    def retranslateUi(self, ticketWindow):
        _translate = QtCore.QCoreApplication.translate
        ticketWindow.setWindowTitle(_translate("ticketWindow", "Ticket Purchase"))
        self.lblName.setText(_translate("ticketWindow", "Enter Name"))
        self.lblAge.setText(_translate("ticketWindow", "Enter Age"))
        self.cmbSelection.setItemText(0, _translate("ticketWindow", "[Seat Type]"))
        self.cmbSelection.setItemText(1, _translate("ticketWindow", "Toplevel"))
        self.cmbSelection.setItemText(2, _translate("ticketWindow", "Midlevel"))
        self.cmbSelection.setItemText(3, _translate("ticketWindow", "Courtside"))
        self.lblSelection.setText(_translate("ticketWindow", "Select Seat Type"))
        self.grpNumberOfTickets.setTitle(_translate("ticketWindow", "Select Number of Tickets"))
        self.rb1.setText(_translate("ticketWindow", "1"))
        self.rb2.setText(_translate("ticketWindow", "2"))
        self.rb3.setText(_translate("ticketWindow", "3"))
        self.btnCost.setText(_translate("ticketWindow", "Show Cost"))
        self.btnPurchase.setText(_translate("ticketWindow", "Purchase"))
        self.btnClear.setText(_translate("ticketWindow", "Clear"))
        self.btnExit.setText(_translate("ticketWindow", "Exit"))
        self.lblTotalCost.setText(_translate("ticketWindow", "Total Cost:"))
        self.tbTicketPurhcase.setTabText(self.tbTicketPurhcase.indexOf(self.tabTicketPurchase), _translate("ticketWindow", "Ticket Purhcase"))
        self.tbTicketPurhcase.setTabText(self.tbTicketPurhcase.indexOf(self.tabPurchasesMade), _translate("ticketWindow", "Purchases Made"))
        
    def load_data(self, file_name):
        try:
            # creating an empty price dictionary
            price = {}
            with open (file_name, "r") as fname:
                for line in fname:
                    seat_type, price_of_ticket = line.strip().split(",")
                    price[seat_type] = int(price_of_ticket)
            return price
            
        #specific exception
        except FileNotFoundError:
            print("The file does not exist.")
        #generic exception
        except Exception as e:
            print(e)            
            
    def calculate_cost(self):
        try:
            current_selection = self.cmbSelection.currentText()
            if(self.rb1.isChecked()):
                number_of_tickets = 1
            elif(self.rb2.isChecked()):
                number_of_tickets = 2
            elif(self.rb3.isChecked()):
                number_of_tickets = 3
            else:
                number_of_tickets = 0
            
            #get price of seat type using dictionary get method/function
            price_of_ticket = self.price_dictionary.get(current_selection)
            total_cost = price_of_ticket * number_of_tickets
            self.txtAge_2.setText("$"+str(total_cost))
        except Exception as e:
            print(e)
            
    def purchase_made(self):
        try:
            name = self.txtName.text()
            age = self.txtAge.text()
            current_selection = self.cmbSelection.currentText()
            if(self.rb1.isChecked()):
                number_of_tickets = 1
            elif(self.rb2.isChecked()):
                number_of_tickets = 2
            elif(self.rb3.isChecked()):
                number_of_tickets = 3
            else:
                number_of_tickets = 0
            
            # \n to write each new purchase to a new line
            with open("purchases_made.txt", "a") as fname:
                fname.write(name+",  "+age+",  "+current_selection+",  "+str(number_of_tickets) + "\n")
        except Exception as e:
            print(e)
        
    def clear(self):
        try:
            self.txtName.clear()
            self.txtAge.clear()
            self.cmbSelection.setCurrentIndex(0)
            self.rb1.setChecked(True)
            self.txtAge_2.clear()
        except Exception as e:
            print(e)
            
    def display_data(self, index):
        try:
            if(index == 0):
                self.lstPurchasesMade.clear()
            else:
              
                with open("purchases_made.txt", "r") as fname:
                    for line in fname:
                        self.lstPurchasesMade.addItem(line)
        except FileNotFoundError:
            print("No purchase data exists.")
        except Exception as e:
            print(e)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ticketWindow = QtWidgets.QMainWindow()
    ui = Ui_ticketWindow()
    ui.setupUi(ticketWindow)
    ticketWindow.show()
    sys.exit(app.exec())
