# Form implementation generated from reading ui file 'fullname.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 812)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(310, 270, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(480, 271, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtFirstName.setFont(font)
        self.txtFirstName.setObjectName("txtFirstName")
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(310, 365, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(480, 360, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtLastName.setFont(font)
        self.txtLastName.setObjectName("txtLastName")
        self.btnFullName = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFullName.setGeometry(QtCore.QRect(642, 397, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnFullName.setFont(font)
        self.btnFullName.setObjectName("btnFullName")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(480, 580, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.txtFullName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFullName.setGeometry(QtCore.QRect(640, 580, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtFullName.setFont(font)
        self.txtFullName.setObjectName("txtFullName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btnFullName.clicked.connect(self.display_full_name)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Full Name"))
        self.lblFirstName.setText(_translate("MainWindow", "Enter First Name"))
        self.lblLastName.setText(_translate("MainWindow", "Enter Last Name"))
        self.btnFullName.setText(_translate("MainWindow", "Full Name"))
        self.lblResult.setText(_translate("MainWindow", "Full Name"))
        
    def display_full_name(self):
        #get the first name enetered by the user in the text box and store it in variable first_name
        first_name = self.txtFirstName.text()
        #get the last name enetered by the user in the text box and store it in variable last_name
        last_name = self.txtLastName.text()
        #add the two names together as a new name
        full_name = first_name + " " + last_name
        #set the text for the result
        self.txtFullName.setText(full_name)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
