# Form implementation generated from reading ui file 'studentperformance.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem
#importing the pymysql package and calling it with an alias "mdb"
import pymysql as mdb


class Ui_studentPerformance(object):
    def setupUi(self, studentPerformance):
        studentPerformance.setObjectName("studentPerformance")
        studentPerformance.resize(1124, 929)
        self.centralwidget = QtWidgets.QWidget(parent=studentPerformance)
        self.centralwidget.setObjectName("centralwidget")
        self.lblId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblId.setGeometry(QtCore.QRect(280, 160, 151, 31))
        self.lblId.setObjectName("lblId")
        self.txtId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtId.setGeometry(QtCore.QRect(450, 160, 113, 31))
        self.txtId.setObjectName("txtId")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(280, 220, 151, 31))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(450, 220, 113, 31))
        self.txtName.setObjectName("txtName")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(280, 280, 151, 31))
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(450, 280, 113, 31))
        self.txtScore.setObjectName("txtScore")
        self.btnInsert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsert.setGeometry(QtCore.QRect(280, 390, 121, 31))
        self.btnInsert.setObjectName("btnInsert")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(450, 390, 121, 31))
        self.btnDisplay.setObjectName("btnDisplay")
        self.studentTableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.studentTableWidget.setGeometry(QtCore.QRect(190, 490, 481, 271))
        self.studentTableWidget.setObjectName("studentTableWidget")
        self.studentTableWidget.setColumnCount(0)
        self.studentTableWidget.setRowCount(0)
        studentPerformance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentPerformance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        studentPerformance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentPerformance)
        self.statusbar.setObjectName("statusbar")
        studentPerformance.setStatusBar(self.statusbar)

        self.retranslateUi(studentPerformance)
        QtCore.QMetaObject.connectSlotsByName(studentPerformance)
        
        self.connection = self.createdbconnection()
        # If the connection was successful, call the add_data method
        if self.connection:
            self.add_data("studentdata.txt")
        self.btnInsert.clicked.connect(self.insert_data)
        self.btnDisplay.clicked.connect(self.display_data)

    def retranslateUi(self, studentPerformance):
        _translate = QtCore.QCoreApplication.translate
        studentPerformance.setWindowTitle(_translate("studentPerformance", "Student Performance"))
        self.lblId.setText(_translate("studentPerformance", "Enter Student ID"))
        self.lblName.setText(_translate("studentPerformance", "Enter Student Name"))
        self.lblScore.setText(_translate("studentPerformance", "Enter Student Score"))
        self.btnInsert.setText(_translate("studentPerformance", "Insert Data"))
        self.btnDisplay.setText(_translate("studentPerformance", "Display Data"))
        
    def createdbconnection(self):
        try:
            connectionobj = mdb.connect(host="localhost", user="dbuser", password="dbuser", database="studentperformancedb")
            print("Connected to database.")
            return connectionobj
        except Exception as e:
            print("Error connecting to database")
            print(e)
            return None
         
    def insert_data(self):
        try:
            student_id = self.txtId.text()
            student_name = self.txtName.text()
            student_score = self.txtScore.text()
            #Add input validation
            
            # create a cursor object
            cursor = self.connection.cursor()
            cursor.execute("insert into studentperformance (studentid, studentname, studentscore) values (%s,%s,%s)", [student_id, student_name, student_score])
            self.connection.commit()
            print("Added data to the table")
            #Clear the text boxes
        except Exception as e:
            print("Error inserting data")
            print(e)
            
    def add_data(self, file_name):
        try:
            cursor = self.connection.cursor()
            with open(file_name, 'r') as fname:
                for line in fname:
                    #trim removes leading and trailing blank spaces
                    #split is the delimiter
                    data_lst = line.split(",")
                    # [107, 'Steve Sides', 89]
                    #add data to database table
                    cursor.execute("insert into studentperformance (studentid, studentname, studentscore) values (%s,%s,%s)", [data_lst[0], data_lst[1], data_lst[2]])
                    self.connection.commit()
                    print("Added data to the table")
        except Exception as e:
            print("There was an error adding data")
            print(e)
            
            
    def display_data(self):
        try:
            cursor = self.connection.cursor()
            cursor.execute("select * from studentperformance")
            results = cursor.fetchall()
            #finding number of rows
            row_count = len(results)
            #finding number of columns
            column_count = len(cursor.description)
            #print(results)
            #print(cursor.description)
            #set row count
            self.studentTableWidget.setRowCount(row_count)
            #set column count
            self.studentTableWidget.setColumnCount(column_count)
            #add column headers
            column_name_lst = ['Id', 'Name', 'Performance']
            #set the column headers for the tableWidget
            self.studentTableWidget.setHorizontalHeaderLabels(column_name_lst)
            
            # enumerate(results) helps access the row number and the row data
            # rowindex and column index start at 0
            
            for rowindex, rowdata in enumerate(results):
                for columnindex, data in enumerate(rowdata):
                    if columnindex == 2:
                        performance = self.get_performance(data)
                        self.studentTableWidget.setItem(rowindex, columnindex, QTableWidgetItem(performance))
                    else:
                        self.studentTableWidget.setItem(rowindex, columnindex, QTableWidgetItem(str(data)))
                        
            
            
            
        except Exception as e:
            print(e)
            
    def get_performance(self, data):
        if data > 80:
            return "Good"
        else:
            return "Not Good"


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentPerformance = QtWidgets.QMainWindow()
    ui = Ui_studentPerformance()
    ui.setupUi(studentPerformance)
    studentPerformance.show()
    sys.exit(app.exec())
