# Form implementation generated from reading ui file 'averagescores.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 866)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(120, 200, 141, 31))
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(290, 205, 113, 21))
        self.txtScore.setObjectName("txtScore")
        self.btnAddScore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddScore.setGeometry(QtCore.QRect(290, 300, 111, 29))
        self.btnAddScore.setObjectName("btnAddScore")
        self.btnAverage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAverage.setGeometry(QtCore.QRect(290, 400, 111, 29))
        self.btnAverage.setObjectName("btnAverage")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(290, 500, 111, 29))
        self.btnClear.setObjectName("btnClear")
        self.lstScores = QtWidgets.QListView(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(660, 200, 271, 331))
        self.lstScores.setObjectName("lstScores")
        self.lblStudentScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentScores.setGeometry(QtCore.QRect(740, 170, 111, 31))
        self.lblStudentScores.setObjectName("lblStudentScores")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #Create an empty list to store each student score
        self.student_scores_lst = []
        
        self.btnAddScore.clicked.connect(self.add_score)
        self.btnAverage.clicked.connect(self.average_score)
        self.btnClear.clicked.connect(self.clear_page)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculate Score"))
        self.lblScore.setText(_translate("MainWindow", "Enter Student Score"))
        self.btnAddScore.setText(_translate("MainWindow", "Add Score"))
        self.btnAverage.setText(_translate("MainWindow", "Average"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.lblStudentScores.setText(_translate("MainWindow", "Student Scores"))
        
    def add_score(self):
        if(self.txtScore.text().isnumeric()):
            #convert the string input to a float
            student_score = float(self.txtScore.text())
            #append the new score to the list
            self.student_scores_lst.append(student_score)
            #add the score to the list widget (I grabbed the wrong list here, but if I replace it with the right one it'll work)
            self.lstScores.addItem(str(student_score))
            
            self.txtScore.clear()
            #brings back the cursor to the text box
            self.txtScore.setFocus()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Calculate Score")
            msg.setText("Please enter a valid score.")
            msg.exec()
            self.txtScore.clear()
            
    def average_score(self):
        if(len(self.student_scores_lst) > 0):
            average_value = sum(self.student_scores_lst)/len(self.student_scores_lst)
            msg = QMessageBox
            msg.setWindowTitle("Calculate Score")
            msg.setText("Average of all scores: " + str(average_value))
            msg.exec()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Calculate Score")
            msg.setText("Please enter scores.")
            msg.exec()
            
    def clear_page(self):
        self.txtScore.clear()
        self.lstScores.clear()
        #also remove all items from the list
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
