# Form implementation generated from reading ui file 'financialplanner2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_financialPlanner(object):
    def setupUi(self, financialPlanner):
        financialPlanner.setObjectName("financialPlanner")
        financialPlanner.resize(1110, 923)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        financialPlanner.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAnnualAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAnnualAmount.setGeometry(QtCore.QRect(240, 220, 151, 51))
        self.lblAnnualAmount.setObjectName("lblAnnualAmount")
        self.lblTotalTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotalTime.setGeometry(QtCore.QRect(240, 290, 151, 51))
        self.lblTotalTime.setObjectName("lblTotalTime")
        self.txtTotalAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotalAmount.setGeometry(QtCore.QRect(410, 230, 113, 31))
        self.txtTotalAmount.setObjectName("txtTotalAmount")
        self.txtTotalTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotalTime.setGeometry(QtCore.QRect(410, 300, 113, 31))
        self.txtTotalTime.setObjectName("txtTotalTime")
        self.lstOutput = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstOutput.setGeometry(QtCore.QRect(680, 260, 301, 371))
        self.lstOutput.setObjectName("lstOutput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(780, 220, 101, 51))
        self.lblOutput.setObjectName("lblOutput")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(410, 430, 111, 81))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(240, 600, 141, 28))
        self.btnClear.setObjectName("btnClear")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(420, 370, 91, 20))
        self.checkBox.setObjectName("checkBox")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(500, 600, 141, 28))
        self.btnExit.setObjectName("btnExit")
        financialPlanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        self.menubar.setObjectName("menubar")
        financialPlanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner)
        self.statusbar.setObjectName("statusbar")
        financialPlanner.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner)
        
        self.btnCalculate.clicked.connect(self.calculate)
        self.btnClear.clicked.connect(self.clear)
        self.btnExit.clicked.connect(self.leave)

    def retranslateUi(self, financialPlanner):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner.setWindowTitle(_translate("financialPlanner", "Financial Planner"))
        self.lblAnnualAmount.setText(_translate("financialPlanner", "Enter Annual Amount"))
        self.lblTotalTime.setText(_translate("financialPlanner", "Enter Years to Invest"))
        self.lblOutput.setText(_translate("financialPlanner", "Portfolio Value"))
        self.btnCalculate.setText(_translate("financialPlanner", "Calculate"))
        self.btnClear.setText(_translate("financialPlanner", "Clear"))
        self.checkBox.setText(_translate("financialPlanner", "Plan 2040"))
        self.btnExit.setText(_translate("financialPlanner", "Exit"))
        
    def calculate(self):
        #define user inputs
        annual_amount = self.txtTotalAmount.text()
        total_time = self.txtTotalTime.text()
        current_portfolio_value = 0
        years = 0        
        #input validations: integers
        if(annual_amount.isdigit() and total_time.isdigit()):
            #transform string into integers
            annual_amount = int(annual_amount)
            total_time = int(total_time)
            #if statement for check box
            if(self.checkBox.isChecked()):
                rate = 7.0
            else:
                rate = 5.0
                
            #create a label for readability
            self.lstOutput.addItem("Yr"+" "+"Current Portfolio Value")
            
            #calculate the portfolio value with a loop    
            for each_year in range(0,total_time):
                current_portfolio_value = (current_portfolio_value + annual_amount) * (1 + rate/100)
                years = (years + 1)
                currency = f"${current_portfolio_value:,.2f}"
                self.lstOutput.addItem(str(years)+"   "+currency)          
            
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Financial Planner")
            msg.setText("Please enter valid amounts and time.")
            msg.exec()
            
    def clear(self):
        #clear input boxes, check box, and output box
        self.txtTotalAmount.clear()
        self.txtTotalTime.clear()
        self.checkBox.setChecked(False)
        self.lstOutput.clear()
        
    def leave(self):
        #close the program
        QtWidgets.QApplication.quit()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner()
    ui.setupUi(financialPlanner)
    financialPlanner.show()
    sys.exit(app.exec())
