# Form implementation generated from reading ui file 'fruitpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 961)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(150, 210, 101, 31))
        self.lblFruit.setObjectName("lblFruit")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(150, 250, 171, 26))
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.lblPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPrice.setGeometry(QtCore.QRect(360, 250, 351, 31))
        self.lblPrice.setText("")
        self.lblPrice.setObjectName("lblPrice")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(150, 320, 101, 31))
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(270, 320, 113, 26))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(150, 390, 93, 29))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(150, 460, 101, 31))
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(260, 460, 113, 26))
        self.txtCost.setObjectName("txtCost")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #dictionary
        self.fruit_price = {"Apple": 2.50, "Banana": 1.25, "Orange": 3.30, "Grapes": 4.20, "Mango": 3.75}
        
        #makes the text box update every time the combo box is changed
        self.cmbFruit.currentIndexChanged.connect(self.display_price)
        
        self.btnCalculate.clicked.connect(self.calculate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fruit Purchase"))
        self.lblFruit.setText(_translate("MainWindow", "Select a Fruit"))
        self.cmbFruit.setItemText(0, _translate("MainWindow", "[Select a Fruit]"))
        self.cmbFruit.setItemText(1, _translate("MainWindow", "Apple"))
        self.cmbFruit.setItemText(2, _translate("MainWindow", "Banana"))
        self.cmbFruit.setItemText(3, _translate("MainWindow", "Orange"))
        self.cmbFruit.setItemText(4, _translate("MainWindow", "Grapes"))
        self.cmbFruit.setItemText(5, _translate("MainWindow", "Mango"))
        self.lblQuantity.setText(_translate("MainWindow", "Enter Quantity"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate"))
        self.lblCost.setText(_translate("MainWindow", "Total Cost:"))
        
    def display_price(self):
        selected_fruit = self.cmbFruit.currentText()
        price_of_fruit = self.fruit_price.get(selected_fruit)
        if(selected_fruit in self.fruit_price.keys()):
            self.lblPrice.setText("Price per pound:" + " " + "$" + str(price_of_fruit))
        else:
            self.lblPrice.setText("")
    
    def calculate(self):
        #give inputs names
        quantity = self.txtQuantity.text()
        selected_fruit = self.cmbFruit.currentText()
        price_of_fruit = self.fruit_price.get(selected_fruit)
        #input validation: picking a fruit
        if(selected_fruit != "[Select a Fruit]"):
            #input validation: picking a quantity
            if(quantity.isdigit()):
                #find the cost
                totalCost = (price_of_fruit * int(quantity))
                totalCost = "{:.2f}".format(totalCost)
                #display result
                self.txtCost.setText("$" + str(totalCost))
            else:
                msg = QMessageBox()
                msg.setWindowTitle("Fruit Purchase")
                msg.setText("Please enter a valid quantity.")
                msg.exec()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Fruit Purchase")
            msg.setText("Please select a fruit.")
            msg.exec()       

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())