# Form implementation generated from reading ui file 'mortalkombat.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Player:
    
    def __init__(self, name, speed, power, agility):
        self.player_name = name
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility
        
    def modify_stats(self, speed, power, agility):
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility


class Ui_mortalKombat(object):
    def setupUi(self, mortalKombat):
        mortalKombat.setObjectName("mortalKombat")
        mortalKombat.resize(1096, 970)
        self.centralwidget = QtWidgets.QWidget(parent=mortalKombat)
        self.centralwidget.setObjectName("centralwidget")
        self.tbLayeredCreation = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbLayeredCreation.setGeometry(QtCore.QRect(0, 0, 1091, 921))
        self.tbLayeredCreation.setObjectName("tbLayeredCreation")
        self.tabCreatePlayer = QtWidgets.QWidget()
        self.tabCreatePlayer.setObjectName("tabCreatePlayer")
        self.lblName = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblName.setGeometry(QtCore.QRect(280, 160, 131, 31))
        self.lblName.setObjectName("lblName")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblSpeed.setGeometry(QtCore.QRect(280, 250, 131, 31))
        self.lblSpeed.setObjectName("lblSpeed")
        self.lblPower = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblPower.setGeometry(QtCore.QRect(280, 340, 131, 31))
        self.lblPower.setObjectName("lblPower")
        self.lblAgility = QtWidgets.QLabel(parent=self.tabCreatePlayer)
        self.lblAgility.setGeometry(QtCore.QRect(280, 430, 131, 31))
        self.lblAgility.setObjectName("lblAgility")
        self.txtName = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtName.setGeometry(QtCore.QRect(480, 160, 113, 31))
        self.txtName.setObjectName("txtName")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtSpeed.setGeometry(QtCore.QRect(480, 250, 113, 31))
        self.txtSpeed.setObjectName("txtSpeed")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtPower.setGeometry(QtCore.QRect(480, 340, 113, 31))
        self.txtPower.setObjectName("txtPower")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tabCreatePlayer)
        self.txtAgility.setGeometry(QtCore.QRect(480, 430, 113, 31))
        self.txtAgility.setObjectName("txtAgility")
        self.btnCreatePlayer = QtWidgets.QPushButton(parent=self.tabCreatePlayer)
        self.btnCreatePlayer.setGeometry(QtCore.QRect(480, 540, 111, 31))
        self.btnCreatePlayer.setObjectName("btnCreatePlayer")
        self.tbLayeredCreation.addTab(self.tabCreatePlayer, "")
        self.tabModifyStats = QtWidgets.QWidget()
        self.tabModifyStats.setObjectName("tabModifyStats")
        self.lstCreatedPlayers = QtWidgets.QListWidget(parent=self.tabModifyStats)
        self.lstCreatedPlayers.setGeometry(QtCore.QRect(360, 50, 321, 251))
        self.lstCreatedPlayers.setObjectName("lstCreatedPlayers")
        self.lblCreatedPlayers = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblCreatedPlayers.setGeometry(QtCore.QRect(460, 20, 111, 31))
        self.lblCreatedPlayers.setObjectName("lblCreatedPlayers")
        self.lblModifyName = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifyName.setGeometry(QtCore.QRect(220, 430, 101, 31))
        self.lblModifyName.setObjectName("lblModifyName")
        self.txtPlayerName = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtPlayerName.setGeometry(QtCore.QRect(220, 470, 113, 31))
        self.txtPlayerName.setObjectName("txtPlayerName")
        self.lblModifySpeed = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifySpeed.setGeometry(QtCore.QRect(370, 430, 101, 31))
        self.lblModifySpeed.setObjectName("lblModifySpeed")
        self.txtPlayerSpeed = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtPlayerSpeed.setGeometry(QtCore.QRect(370, 470, 113, 31))
        self.txtPlayerSpeed.setObjectName("txtPlayerSpeed")
        self.txtPlayerPower = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtPlayerPower.setGeometry(QtCore.QRect(520, 470, 113, 31))
        self.txtPlayerPower.setObjectName("txtPlayerPower")
        self.txtPlayerAgility = QtWidgets.QLineEdit(parent=self.tabModifyStats)
        self.txtPlayerAgility.setGeometry(QtCore.QRect(670, 470, 113, 31))
        self.txtPlayerAgility.setObjectName("txtPlayerAgility")
        self.lblModifyPower = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifyPower.setGeometry(QtCore.QRect(520, 430, 101, 31))
        self.lblModifyPower.setObjectName("lblModifyPower")
        self.lblModifyAgility = QtWidgets.QLabel(parent=self.tabModifyStats)
        self.lblModifyAgility.setGeometry(QtCore.QRect(670, 430, 101, 31))
        self.lblModifyAgility.setObjectName("lblModifyAgility")
        self.btnModifyStats = QtWidgets.QPushButton(parent=self.tabModifyStats)
        self.btnModifyStats.setGeometry(QtCore.QRect(452, 620, 111, 31))
        self.btnModifyStats.setObjectName("btnModifyStats")
        self.tbLayeredCreation.addTab(self.tabModifyStats, "")
        mortalKombat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mortalKombat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 26))
        self.menubar.setObjectName("menubar")
        mortalKombat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mortalKombat)
        self.statusbar.setObjectName("statusbar")
        mortalKombat.setStatusBar(self.statusbar)

        self.retranslateUi(mortalKombat)
        self.tbLayeredCreation.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mortalKombat)
        
        # create an empty dictionary to store player objects when created_players
        self.created_players = {}
        # the button click event
        self.btnCreatePlayer.clicked.connect(self.create_player)
        # list item clicked event
        self.lstCreatedPlayers.itemClicked.connect(self.display_stats)
        
        self.btnModifyStats.clicked.connect(self.modify_stats)

    def retranslateUi(self, mortalKombat):
        _translate = QtCore.QCoreApplication.translate
        mortalKombat.setWindowTitle(_translate("mortalKombat", "Mortal Kombat"))
        self.lblName.setText(_translate("mortalKombat", "Enter Player Name"))
        self.lblSpeed.setText(_translate("mortalKombat", "Enter Player Speed"))
        self.lblPower.setText(_translate("mortalKombat", "Enter Player Power"))
        self.lblAgility.setText(_translate("mortalKombat", "Enter Player Agility"))
        self.btnCreatePlayer.setText(_translate("mortalKombat", "Create Player"))
        self.tbLayeredCreation.setTabText(self.tbLayeredCreation.indexOf(self.tabCreatePlayer), _translate("mortalKombat", "Create Player"))
        self.lblCreatedPlayers.setText(_translate("mortalKombat", "Created Players"))
        self.lblModifyName.setText(_translate("mortalKombat", "Player Name"))
        self.lblModifySpeed.setText(_translate("mortalKombat", "Player Speed"))
        self.lblModifyPower.setText(_translate("mortalKombat", "Player Power"))
        self.lblModifyAgility.setText(_translate("mortalKombat", "Player Agility"))
        self.btnModifyStats.setText(_translate("mortalKombat", "Modify Stats"))
        self.tbLayeredCreation.setTabText(self.tbLayeredCreation.indexOf(self.tabModifyStats), _translate("mortalKombat", "Modify Stats"))
        
    def create_player(self):
        # To Do: add validations and exception handling block
        name = self.txtName.text()
        speed = self.txtSpeed.text()
        power = self.txtPower.text()
        agility = self.txtAgility.text()
        
        player_object = Player(name, speed, power, agility)
        # the dictionary will have player name as the key and player object as the value
        self.created_players[name] = player_object
        self.lstCreatedPlayers.addItem(name)
        
        # Display a message box: Player Created
        
    def display_stats(self, item):
        # get the name of the current selected player in the list widget
        selected_player = item.text()
        player_object = self.created_players.get(selected_player)
        self.txtPlayerName.setText(player_object.player_name)
        self.txtPlayerSpeed.setText(player_object.player_speed)
        self.txtPlayerPower.setText(player_object.player_power)
        self.txtPlayerAgility.setText(player_object.player_agility)
        
    #write the modify_stats method to modify stats
    def modify_stats(self):
        name = self.txtPlayerName.text()
        speed = self.txtPlayerSpeed.text()
        power = self.txtPlayerPower.text()
        agility = self.txtPlayerAgility.text()
        player_object = self.created_players.get(name)
        player_object.modify_stats(speed, power, agility)
        self.created_players[name] = player_object


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mortalKombat = QtWidgets.QMainWindow()
    ui = Ui_mortalKombat()
    ui.setupUi(mortalKombat)
    mortalKombat.show()
    sys.exit(app.exec())
