# Form implementation generated from reading ui file 'helloworld.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import QMessageBox


class Ui_HelloWorld(object):
    def setupUi(self, HelloWorld):
        HelloWorld.setObjectName("HelloWorld")
        HelloWorld.resize(1115, 788)
        self.centralwidget = QtWidgets.QWidget(parent=HelloWorld)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGreeting = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGreeting.setGeometry(QtCore.QRect(410, 360, 161, 51))
        self.btnGreeting.setObjectName("btnGreeting")
        HelloWorld.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=HelloWorld)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 26))
        self.menubar.setObjectName("menubar")
        HelloWorld.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=HelloWorld)
        self.statusbar.setObjectName("statusbar")
        HelloWorld.setStatusBar(self.statusbar)

        self.retranslateUi(HelloWorld)
        QtCore.QMetaObject.connectSlotsByName(HelloWorld)
        
        # when the button is clicked call the display_message function
        self.btnGreeting.clicked.connect(self.display_message)

    def retranslateUi(self, HelloWorld):
        _translate = QtCore.QCoreApplication.translate
        HelloWorld.setWindowTitle(_translate("HelloWorld", "Hello World"))
        self.btnGreeting.setText(_translate("HelloWorld", "Click Me"))
        
    # self: refers to the function being part of the application
    
    def display_message(self):
        # create a new instance of a message box
        msg = QMessageBox()
        # set the text for the message box to display to the user
        msg.setText("Hello World")
        #execute the message box to display the message box to the user
        msg.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelloWorld = QtWidgets.QMainWindow()
    ui = Ui_HelloWorld()
    ui.setupUi(HelloWorld)
    HelloWorld.show()
    sys.exit(app.exec())
