# Form implementation generated from reading ui file 'gradecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 867)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(260, 300, 121, 31))
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(440, 300, 113, 22))
        self.txtScore.setObjectName("txtScore")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(440, 380, 111, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(260, 470, 121, 31))
        self.lblGrade.setObjectName("lblGrade")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(440, 470, 113, 22))
        self.txtGrade.setObjectName("txtGrade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btnCalculate.clicked.connect(self.calculateGrade)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grade Calculator"))
        self.lblScore.setText(_translate("MainWindow", "Enter Student Score"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate Grade"))
        self.lblGrade.setText(_translate("MainWindow", "Enter Student Score"))
        
    def calculateGrade(self):
        #assign names to text box
        student_score = self.txtScore.text()
        grade = ""
        msg = QMessageBox()
        msg.setWindowTitle("Grade Calculator")
        #input validations, numerical, 1-100
        if(student_score.isdigit()):
            student_score = int(student_score)
            if(student_score < 101):
                if(student_score >= 90):
                    grade = "A"
                elif(student_score >= 80):
                    grade = "B"
                elif(student_score >= 70):
                    grade = "C"
                elif(student_score >= 60):
                    grade = "D"
                else:
                    grade = "F"
                self.txtGrade.setText(grade)
            else:
                msg.setText("Please enter a number between 1 and 100.")
                msg.exec()
        else:
            msg.setText("Please enter a valid score.")
            msg.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
